name: erp_system
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: 
  intl:
  pinput: 
  fl_chart:
  provider:
  go_router:
  data_table_2: 
  image_picker: 
  flutter_bloc:
  firebase_auth:
  firebase_core:
  table_calendar:
  cloud_firestore:
  cupertino_icons: 
  dropdown_button2:
  pluto_grid: 7.0.0
  form_field_validator:
  bloc: ^8.1.4
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  
flutter:
  uses-material-design: true
  
      

  assets:
    - assets/images/
